name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Sesuaikan dengan versi PHP Anda
        tools: composer:v2

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Clear Composer Cache
      run: composer clear-cache

    - name: Update Dependencies
      run: composer update --no-ansi --no-interaction --no-progress --prefer-dist

    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

    - name: Install Doctrine DBAL
      run: composer require doctrine/dbal

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Set Directory Permissions
      run: chmod -R ug+rwx storage bootstrap/cache

    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Run Migrations
      run: php artisan migrate

    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
